import FWCore.ParameterSet.Config as cms
import getpass, os
pwd = os.getcwd()
os.chdir("UserCode/IIHETree/")
username = getpass.getuser()
os.system("git log -n 1 | head -n 1 | awk '{print $2}' > /tmp/%s_git.hash"%username)
f = open('/tmp/git.hash')
git_hash = f.read().rstrip('\n')
print 'Using git hash: ' , git_hash
os.chdir(pwd)
IIHEAnalysis = cms.EDAnalyzer("IIHEAnalysis",
    debug         = cms.bool(True),
    beamSpot      = cms.InputTag("offlineBeamSpot"),
    primaryVertex = cms.InputTag('offlinePrimaryVertices'),
    git_hash = cms.string(git_hash),
    
    HEEP_EcalHcal1EffAreaBarrel  = cms.untracked.double(0.28),
    HEEP_EcalHcal1EffAreaEndcaps = cms.untracked.double(0.28),
    
    HEEP_EtThresholdBarrel_41 = cms.untracked.double( 35.0 ),
    HEEP_EtThresholdEndcap_41 = cms.untracked.double( 35.0 ),
    HEEP_EtThresholdBarrel_50 = cms.untracked.double( 35.0 ),
    HEEP_EtThresholdEndcap_50 = cms.untracked.double( 35.0 ),
    
    HEEP_barrelEtaUpper_41 = cms.untracked.double( 1.442  ),
    HEEP_endcapEtaLower_41 = cms.untracked.double( 1.56   ),
    HEEP_endcapEtaUpper_41 = cms.untracked.double( 2.5    ),
    HEEP_barrelEtaUpper_50 = cms.untracked.double( 1.4442 ),
    HEEP_endcapEtaLower_50 = cms.untracked.double( 1.566  ),
    HEEP_endcapEtaUpper_50 = cms.untracked.double( 2.5    ),
    
    HEEP_dEtaInThresholdBarrel_41         = cms.untracked.double( 0.005   ),
    HEEP_dEtaInThresholdEndcap_41         = cms.untracked.double( 0.007   ),
    HEEP_dEtaInConstantTermBarrel_50_50ns = cms.untracked.double( 0.016   ),
    HEEP_dEtaInLinearTermBarrel_50_50ns   = cms.untracked.double( 0.0001  ),
    HEEP_dEtaInCutoffTermBarrel_50_50ns   = cms.untracked.double( 0.004   ),
    HEEP_dEtaInThresholdEndcap_50_50ns    = cms.untracked.double( 0.02    ),
    HEEP_dEtaInConstantTermBarrel_50_25ns = cms.untracked.double( 0.016   ),
    HEEP_dEtaInLinearTermBarrel_50_25ns   = cms.untracked.double( 0.0001  ),
    HEEP_dEtaInCutoffTermBarrel_50_25ns   = cms.untracked.double( 0.004   ),
    HEEP_dEtaInConstantTermEndcap_50_25ns = cms.untracked.double( 0.016   ),
    HEEP_dEtaInLinearTermEndcap_50_25ns   = cms.untracked.double( 0.0001  ),
    HEEP_dEtaInCutoffTermEndcap_50_25ns   = cms.untracked.double( 0.004   ),
    HEEP_dEtaInConstantTermBarrel_50      = cms.untracked.double( 0.016   ),
    HEEP_dEtaInLinearTermBarrel_50        = cms.untracked.double( 0.0001  ),
    HEEP_dEtaInCutoffTermBarrel_50        = cms.untracked.double( 0.004   ),
    HEEP_dEtaInConstantTermEndcap_50      = cms.untracked.double( 0.015   ),
    HEEP_dEtaInLinearTermEndcap_50        = cms.untracked.double( 0.00085 ),
    HEEP_dEtaInCutoffTermEndcap_50        = cms.untracked.double( 0.006   ),
    HEEP_dEtaInThresholdBarrel_50         = cms.untracked.double( 0.004   ),
    HEEP_dEtaInThresholdEndcap_50         = cms.untracked.double( 0.006   ),
    
    HEEP_dPhiInThresholdBarrel_41      = cms.untracked.double( 0.06 ),
    HEEP_dPhiInThresholdEndcap_41      = cms.untracked.double( 0.06 ),
    HEEP_dPhiInThresholdBarrel_50_50ns = cms.untracked.double( 0.06 ),
    HEEP_dPhiInThresholdEndcap_50_50ns = cms.untracked.double( 0.15 ),
    HEEP_dPhiInThresholdBarrel_50_25ns = cms.untracked.double( 0.06 ),
    HEEP_dPhiInThresholdEndcap_50_25ns = cms.untracked.double( 0.06 ),
    HEEP_dPhiInThresholdBarrel_50      = cms.untracked.double( 0.06 ),
    HEEP_dPhiInThresholdEndcap_50      = cms.untracked.double( 0.06 ),
    HEEP_dPhiInThresholdBarrel_51      = cms.untracked.double( 0.06 ),
    HEEP_dPhiInThresholdEndcap_51      = cms.untracked.double( 0.06 ),
    
    HEEP_HOverEThresholdBarrel_41           = cms.untracked.double(  0.05 ),
    HEEP_HOverEThresholdEndcap_41           = cms.untracked.double(  0.05 ),
    HEEP_HOverEReciprocalTermBarrel_50_50ns = cms.untracked.double(  2.0  ),
    HEEP_HOverEConstantTermBarrel_50_50ns   = cms.untracked.double(  0.05 ),
    HEEP_HOverEReciprocalTermEndcap_50_50ns = cms.untracked.double( 12.5  ),
    HEEP_HOverEConstantTermEndcap_50_50ns   = cms.untracked.double(  0.05 ),
    HEEP_HOverEReciprocalTermBarrel_50_25ns = cms.untracked.double(  2.0  ),
    HEEP_HOverEConstantTermBarrel_50_25ns   = cms.untracked.double(  0.05 ),
    HEEP_HOverEReciprocalTermEndcap_50_25ns = cms.untracked.double( 12.5  ),
    HEEP_HOverEConstantTermEndcap_50_25ns   = cms.untracked.double(  0.05 ),
    HEEP_HOverEReciprocalTermBarrel_50      = cms.untracked.double(  2.0  ),
    HEEP_HOverEConstantTermBarrel_50        = cms.untracked.double(  0.05 ),
    HEEP_HOverEReciprocalTermEndcap_50      = cms.untracked.double( 12.5  ),
    HEEP_HOverEConstantTermEndcap_50        = cms.untracked.double(  0.05 ),
    HEEP_HOverEReciprocalTermBarrel_51      = cms.untracked.double(  2.0  ),
    HEEP_HOverEConstantTermBarrel_51        = cms.untracked.double(  0.05 ),
    HEEP_HOverEReciprocalTermEndcap_51      = cms.untracked.double( 12.5  ),
    HEEP_HOverEConstantTermEndcap_51        = cms.untracked.double(  0.05 ),
    
    HEEP_SigmaIetaIetaThreshold_41      = cms.untracked.double( 0.03 ),
    HEEP_SigmaIetaIetaThreshold_50_50ns = cms.untracked.double( 0.03 ),
    HEEP_SigmaIetaIetaThreshold_50_25ns = cms.untracked.double( 0.03 ),
    HEEP_SigmaIetaIetaThreshold_50      = cms.untracked.double( 0.03 ),
    HEEP_SigmaIetaIetaThreshold_51      = cms.untracked.double( 0.03 ),
    
    HEEP_E1x5threshold_41      = cms.untracked.double( 0.83 ),
    HEEP_E2x5threshold_41      = cms.untracked.double( 0.94 ),
    HEEP_E1x5threshold_50_50ns = cms.untracked.double( 0.83 ),
    HEEP_E2x5threshold_50_50ns = cms.untracked.double( 0.94 ),
    HEEP_E1x5threshold_50_25ns = cms.untracked.double( 0.83 ),
    HEEP_E2x5threshold_50_25ns = cms.untracked.double( 0.94 ),
    HEEP_E1x5threshold_50      = cms.untracked.double( 0.83 ),
    HEEP_E2x5threshold_50      = cms.untracked.double( 0.94 ),
    HEEP_E1x5threshold_51      = cms.untracked.double( 0.83 ),
    HEEP_E2x5threshold_51      = cms.untracked.double( 0.94 ),
    
    HEEP_isolEMHadDepth1ConstantTermBarrel_41            = cms.untracked.double( 2.0  ),
    HEEP_isolEMHadDepth1ConstantTermEndcapLowEt_41       = cms.untracked.double( 2.5  ),
    HEEP_isolEMHadDepth1ConstantTermEndcapHighEt_41      = cms.untracked.double( 2.5  ),
    HEEP_isolEMHadDepth1LinearTermBarrel_41              = cms.untracked.double( 0.03 ),
    HEEP_isolEMHadDepth1LinearTermEndcap_41              = cms.untracked.double( 0.03 ),
    HEEP_isolEMHadDepth1OffsetTermEndcap_41              = cms.untracked.double( 50.0 ),
    HEEP_isolEMHadDepth1ConstantTermBarrel_50_50ns       = cms.untracked.double( 2.0  ),
    HEEP_isolEMHadDepth1ConstantTermEndcapLowEt_50_50ns  = cms.untracked.double( 2.5  ),
    HEEP_isolEMHadDepth1ConstantTermEndcapHighEt_50_50ns = cms.untracked.double( 2.5  ),
    HEEP_isolEMHadDepth1LinearTermBarrel_50_50ns         = cms.untracked.double( 0.03 ),
    HEEP_isolEMHadDepth1LinearTermEndcap_50_50ns         = cms.untracked.double( 0.03 ),
    HEEP_isolEMHadDepth1OffsetTermEndcap_50_50ns         = cms.untracked.double( 50.0 ),
    HEEP_isolEMHadDepth1ConstantTermBarrel_50_25ns       = cms.untracked.double( 2.0  ),
    HEEP_isolEMHadDepth1ConstantTermEndcapLowEt_50_25ns  = cms.untracked.double( 2.5  ),
    HEEP_isolEMHadDepth1ConstantTermEndcapHighEt_50_25ns = cms.untracked.double( 2.5  ),
    HEEP_isolEMHadDepth1LinearTermBarrel_50_25ns         = cms.untracked.double( 0.03 ),
    HEEP_isolEMHadDepth1LinearTermEndcap_50_25ns         = cms.untracked.double( 0.03 ),
    HEEP_isolEMHadDepth1OffsetTermEndcap_50_25ns         = cms.untracked.double( 50.0 ),
    HEEP_isolEMHadDepth1ConstantTermBarrel_50            = cms.untracked.double( 2.0  ),
    HEEP_isolEMHadDepth1ConstantTermEndcapLowEt_50       = cms.untracked.double( 2.5  ),
    HEEP_isolEMHadDepth1ConstantTermEndcapHighEt_50      = cms.untracked.double( 2.5  ),
    HEEP_isolEMHadDepth1LinearTermBarrel_50              = cms.untracked.double( 0.03 ),
    HEEP_isolEMHadDepth1LinearTermEndcap_50              = cms.untracked.double( 0.03 ),
    HEEP_isolEMHadDepth1OffsetTermEndcap_50              = cms.untracked.double( 50.0 ),
    HEEP_isolEMHadDepth1ConstantTermBarrel_51            = cms.untracked.double( 2.0  ),
    HEEP_isolEMHadDepth1ConstantTermEndcapLowEt_51       = cms.untracked.double( 2.5  ),
    HEEP_isolEMHadDepth1ConstantTermEndcapHighEt_51      = cms.untracked.double( 2.5  ),
    HEEP_isolEMHadDepth1LinearTermBarrel_51              = cms.untracked.double( 0.03 ),
    HEEP_isolEMHadDepth1LinearTermEndcap_51              = cms.untracked.double( 0.03 ),
    HEEP_isolEMHadDepth1OffsetTermEndcap_51              = cms.untracked.double( 50.0 ),
    
    HEEP_IsolPtTrksThresholdBarrel_41      = cms.untracked.double( 5.0 ),
    HEEP_IsolPtTrksThresholdEndcap_41      = cms.untracked.double( 5.0 ),
    HEEP_IsolPtTrksThresholdBarrel_50_50ns = cms.untracked.double( 5.0 ),
    HEEP_IsolPtTrksThresholdEndcap_50_50ns = cms.untracked.double( 5.0 ),
    HEEP_IsolPtTrksThresholdBarrel_50_25ns = cms.untracked.double( 5.0 ),
    HEEP_IsolPtTrksThresholdEndcap_50_25ns = cms.untracked.double( 5.0 ),
    HEEP_IsolPtTrksThresholdBarrel_50      = cms.untracked.double( 5.0 ),
    HEEP_IsolPtTrksThresholdEndcap_50      = cms.untracked.double( 5.0 ),
    HEEP_IsolPtTrksThresholdBarrel_51      = cms.untracked.double( 5.0 ),
    HEEP_IsolPtTrksThresholdEndcap_51      = cms.untracked.double( 5.0 ),
    
    HEEP_missingHitsThreshold_41      = cms.untracked.double( 1 ),
    HEEP_missingHitsThreshold_50_50ns = cms.untracked.double( 1 ),
    HEEP_missingHitsThreshold_50_25ns = cms.untracked.double( 1 ),
    HEEP_missingHitsThreshold_50      = cms.untracked.double( 1 ),
    HEEP_missingHitsThreshold_51      = cms.untracked.double( 1 ),
    
    HEEP_dxyFirstPvThresholdBarrel_41      = cms.untracked.double( 0.02 ),
    HEEP_dxyFirstPvThresholdEndcap_41      = cms.untracked.double( 0.05 ),
    HEEP_dxyFirstPvThresholdBarrel_50_50ns = cms.untracked.double( 0.02 ),
    HEEP_dxyFirstPvThresholdEndcap_50_50ns = cms.untracked.double( 0.05 ),
    HEEP_dxyFirstPvThresholdBarrel_50_25ns = cms.untracked.double( 0.02 ),
    HEEP_dxyFirstPvThresholdEndcap_50_25ns = cms.untracked.double( 0.05 ),
    HEEP_dxyFirstPvThresholdBarrel_50      = cms.untracked.double( 0.02 ),
    HEEP_dxyFirstPvThresholdEndcap_50      = cms.untracked.double( 0.05 ),
    HEEP_dxyFirstPvThresholdBarrel_51      = cms.untracked.double( 0.02 ),
    HEEP_dxyFirstPvThresholdEndcap_51      = cms.untracked.double( 0.05 )
)
